### ISSUE TITLE
syntax error at or near "89477"

### ISSUE THREAD

**Issue by Geoneer** [Geoneer/smrtmps_ws#101]
19-12-2018 01:16:16 || ERROR || 42601: syntax error at or near "89477" ||  ||    at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Npgsql.NpgsqlDataReader.<NextResult>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.<ExecuteDbDataReader>d__100.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.<ExecuteScalar>d__95.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.ExecuteScalar()
   at Graph_Database.RunQuery(String query, String connection, Boolean scalar) in d:\repos\smartmaps_ws\App_Code\Graph\Database.cs:line 103 || Npgsql || Set graph_path = graph;MERGE (point:events{attending_count: '3493', cover_offset_x: '50', cover_offset_y: '38', cover_source: 'https://scontent.xx.fbcdn.net/v/t1.0-9/11140279_411299062375873_807993787473750905_n.jpg?_nc_cat=108&_nc_ht=scontent.xx&oh=2e8602d64c562e767dc623960649005c&oe=5C9DA7A3', cover_id: '411299062375873', declined_count: '0', description: 'rijd jij ook zo vaak in de sloot doe dan hier aan mee', id: '1666964263525027', interested_count: '8974', name: 'Wk in de sloot rijden', place_name: 'Sloten', place_location_city: 'Sloten', place_location_country: 'Netherlands', latitude: 52,89477, longitude: 5,64483, place_id: '109174129104657', start_time: '18-10-2030 00:10:00', type: 'events', updated_time: '15-8-2018 05:32:35'}) RETURN id(point);

**Comment by Geoneer** [comment]
check this: latitude: 52,**89477**, longitude: 5,64483

**Comment by Geoneer** [comment]
it's because of the lat / lon decimal. So change the system regional decimals from [ , ] to [ . ]

**Comment by Geoneer** [comment]
![image](https://user-images.githubusercontent.com/218929/50191094-794c5200-032c-11e9-8185-b14d30d2b6c2.png)

**Comment by Geoneer** [comment]
![image](https://user-images.githubusercontent.com/218929/50191112-8d904f00-032c-11e9-808a-bdc520e00d37.png)

**Comment by Geoneer** [comment]
mmmm still same error:

19-12-2018 01:29:30 || ERROR || 42601: syntax error at or near "89477" ||  ||    at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Npgsql.NpgsqlDataReader.<NextResult>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.<ExecuteDbDataReader>d__100.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.<ExecuteScalar>d__95.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.ExecuteScalar()
   at Graph_Database.RunQuery(String query, String connection, Boolean scalar) in d:\repos\smartmaps_ws\App_Code\Graph\Database.cs:line 103 || Npgsql || Set graph_path = graph;MERGE (point:events{attending_count: '3493', cover_offset_x: '50', cover_offset_y: '38', cover_source: 'https://scontent.xx.fbcdn.net/v/t1.0-9/11140279_411299062375873_807993787473750905_n.jpg?_nc_cat=108&_nc_ht=scontent.xx&oh=2e8602d64c562e767dc623960649005c&oe=5C9DA7A3', cover_id: '411299062375873', declined_count: '0', description: 'rijd jij ook zo vaak in de sloot doe dan hier aan mee', id: '1666964263525027', interested_count: '8974', name: 'Wk in de sloot rijden', place_name: 'Sloten', place_location_city: 'Sloten', place_location_country: 'Netherlands', latitude: 52,89477, longitude: 5,64483, place_id: '109174129104657', start_time: '18-10-2030 00:10:00', type: 'events', updated_time: '15-8-2018 05:32:35'}) RETURN id(point);

**Comment by Geoneer** [comment]
how about to put the lat / lon values between quotes? All the other items are also between quotes...

**Comment by Geoneer** [comment]
try this:

![image](https://user-images.githubusercontent.com/218929/50192301-f4fccd80-0331-11e9-9c4a-e345ef7731ff.png)

**Comment by Geoneer** [comment]
call it a day.

**Comment by Geoneer** [comment]
did not get the error anymore.
