### ISSUE TITLE
Cannot perform runtime binding on a null reference 

### ISSUE THREAD

**Issue by Geoneer** [Geoneer/smrtmps_ws#102]
12/19/2018 4:54:28 PM || ERROR || Cannot perform runtime binding on a null reference ||  ||    at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at CallSite.Target(Closure , CallSite , Object )
   at Graph_Pois.SavePois(Object parent, String from, Object results, String type, FieldsList fieldsList) in d:\repos\smartmaps_ws\App_Code\Graph\Pois.cs:line 149
   at CallSite.Target(Closure , CallSite , Type , Object , String , Object , String , FieldsList )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid6[T0,T1,T2,T3,T4,T5](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at Graph_Pois.SavePoisTypes(Object parent, String from, Object data, String type) in d:\repos\smartmaps_ws\App_Code\Graph\Pois.cs:line 130
   at CallSite.Target(Closure , CallSite , Type , Object , String , Object , String )
   at Graph_Pois.BuildUpQuery(Object parent, Object data, String from) in d:\repos\smartmaps_ws\App_Code\Graph\Pois.cs:line 116
   at CallSite.Target(Closure , CallSite , Type , Object , Object , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid4[T0,T1,T2,T3](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at Graph_Pois.main(String uid, String token, Boolean dev) in d:\repos\smartmaps_ws\App_Code\Graph\Pois.cs:line 36 || Anonymously Hosted DynamicMethods Assembly ||

**Comment by Geoneer** [comment]
if (data.location.latitude != null && data.location.longitude != null)
                    {
                        InsertDataInGraphDatabase(data, parent, from, type.ToLower(), fieldsList, data.location);
                    }

**Comment by Geoneer** [comment]
data.location.latitude data.location is null.. so latitude is causing the error.
