### ISSUE TITLE
ERROR || 3D000: database "smartmaps" does not exist

### ISSUE THREAD

**Issue by Geoneer** [Geoneer/smrtmps_ws#111]
12/25/2018 12:39:22 AM || ERROR || 3D000: database "smartmaps" does not exist ||  ||    at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__149.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at Graph_Database.RunQuery(String query, String connection, Boolean scalar) in d:\repos\smartmaps_ws\App_Code\Graph\Database.cs:line 97 || Npgsql || Set graph_path = graph;MATCH (p:users{uid:'10155235285749894'}) RETURN id(p)

**Comment by Geoneer** [comment]
needs to be on the Graph server... so check this in pgadmin.

**Comment by Geoneer** [comment]
1. create database [smartmaps] with schema [graph]
2. create database [smartmaps] on postgis server.
