### ISSUE TITLE
Adding fields of the types from facebook again. 

### ISSUE THREAD

**Issue by Geoneer** [Geoneer/smrtmps_ws#45]
try to add the fields from a dynamic request. Now it's hardcoded in facebook.cs.

#10 #26 #3

**Comment by Geoneer** [comment]
https://stackoverflow.com/questions/5097085/list-of-facebook-fields-returned-by-social-graph-api

**Comment by Geoneer** [comment]
it's not possible. So end this.

**Comment by Geoneer** [comment]
getFields works for the userfields. Now check likes.

**Comment by Geoneer** [comment]
Facebook.FacebookOAuthException
  HResult=0x80131500
  Message=(OAuthException - #10) (#10) To use 'Page Public Content Access', your use of this endpoint must be reviewed and approved by Facebook. To submit this 'Page Public Content Access' feature for review please read our documentation on reviewable features: https://developers.facebook.com/docs/apps/review.
  Source=App_Code.lkjiu9tg
  StackTrace:
   at FacebookManager.getFields(String id, FacebookClient _fb) in d:\repos\smartmaps_ws\App_Code\Facebook.cs:line 186
   at WebService._test() in d:\repos\smartmaps_ws\App_Code\WebService.cs:line 73

**Comment by Geoneer** [comment]
facebook doesn't want to use this from the api.
