### ISSUE TITLE
The stream is currently in use by a previous operation on the stream.

### ISSUE THREAD

**Issue by Geoneer** [Geoneer/smrtmps_ws#58]
System.InvalidOperationException
  HResult=0x80131509
  Message=The stream is currently in use by a previous operation on the stream.
  Source=mscorlib
  StackTrace:
   at System.IO.StreamWriter.CheckAsyncTaskInProgress()
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.StreamWriter.Close()
   at LogManager.log(String level, Exception ex, String msg) in d:\repos\smartmaps_ws\App_Code\logger.cs:line 50
   at Graph_Pois.main(String uid, String token) in d:\repos\smartmaps_ws\App_Code\Graph\Pois.cs:line 29
   at WebService.SaveInterests(String uid, String token) in d:\repos\smartmaps_ws\App_Code\WebService.cs:line 76

**Comment by Geoneer** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.io.streamwriter.writelineasync?view=netframework-4.7.2

**Comment by Geoneer** [comment]
bug is fixed. But new bug is there.
