### ISSUE TITLE
Application request limit reached. Setup testdata to develop with.

### ISSUE THREAD

**Issue by Geoneer** [Geoneer/smrtmps_ws#94]
3-12-2018 15:13:04 || ERROR || (OAuthException - #4) (#4) Application request limit reached ||  ||    at Facebook.FacebookClient.ProcessResponse(HttpHelper httpHelper, String responseString, Type resultType, Boolean containsEtag, IList`1 batchEtags)
   at Facebook.FacebookClient.Api(HttpMethod httpMethod, String path, Object parameters, Type resultType)
   at Facebook.FacebookClient.Get(String path, Object parameters, Type resultType)
   at Facebook.FacebookClient.Get(String path, Object parameters)
   at FacebookManager.GetDataFromApi(String uid, String token, String param) in d:\repos\smartmaps_ws\App_Code\Facebook.cs:line 154
   at Graph_Pois.main(String uid, String token) in d:\repos\smartmaps_ws\App_Code\Graph\Pois.cs:line 21 || Facebook ||

**Comment by Geoneer** [comment]
convert the string to a dynamic object

https://www.google.nl/search?ei=xT0FXPuTHsrosAfnxoPIDA&q=%27string%27+does+not+contain+a+definition+for+%27Keys%27&oq=%27string%27+does+not+contain+a+definition+for+%27Keys%27&gs_l=psy-ab.3...2555.8720..9644...0.0..0.91.277.4......0....1..gws-wiz.......0i22i30.TFCm8iTV3c0

**Comment by Geoneer** [comment]
https://stackoverflow.com/questions/4535840/deserialize-json-object-into-dynamic-object-using-json-net

**Comment by Geoneer** [comment]
how about to add a limit return value on the returned objects? I only need a few of them.

**Comment by Geoneer** [comment]
https://developers.facebook.com/docs/graph-api/advanced/rate-limiting/

**Comment by Geoneer** [comment]
try to implement this during dev.
