### ISSUE TITLE
Could not load file or assembly 'netstandard, Version=2.0.0.0

### ISSUE THREAD

**Issue by Geoneer** [Geoneer/smrtmps_ws#97]
during reinstallation of the laptop I've got this bug:

Could not load file or assembly 'netstandard, Version=2.0.0.0

**Comment by Geoneer** [comment]
17-12-2018 13:57:08 || ERROR || Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. ||  ||    at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<Open>g__OpenLong|0()
   at Npgsql.NpgsqlConnection.Open(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.Open()
   at Graph_Database.RunQuery(String query, String connection, Boolean scalar) in d:\repos\smartmaps_ws\App_Code\Graph\Database.cs:line 97 || Npgsql || DROP GRAPH PUBLIC CASCADE;
